### ISSUE TITLE
wrong version in manifest

### ISSUE THREAD

**Issue by pyramus** [andyault/sketch-adjusttofit#3]
hey i think you accidentally put in the wrong version in the manifest file, leading to sketch not updating the plugin.

**Comment by simon-e3** [comment]
this update notification is so annoying! haha

**Comment by andyault** [comment]
hey guys, thanks for the help and the support.

I just pushed a new update that should fix this issue - it'll be [v1.2.2](https://github.com/andyault/sketch-adjusttofit/releases/tag/v1.2.2).

if you guys were curious, the reason I had so much trouble was because the `skpm publish` command automatically updates the `package.json` version, makes a git commit and adds a git tag, but it doesn't update the `manifest.json` version. updating this file manually (what @pyramus found) was able to fix it.

thanks again for the help, and let me know if you guys have any other issues/requests!
